version: "3.9"

services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # admin.js
      - "8082:8080"  # main.js
      - "8083:8081"  # chat.js
    volumes:
      - ./database:/app/database
    environment:
      NODE_ENV: development
    networks:
      - app-network

  backend2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3000"  # admin.js
      - "8085:8080"  # main.js
      - "8086:8081"  # chat.js
    volumes:
      - ./database:/app/database
    environment:
      NODE_ENV: development
    networks:
      - app-network

  backend3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3007:3000"  # admin.js
      - "8088:8080"  # main.js
      - "8089:8081"  # chat.js
    volumes:
      - ./database:/app/database
    environment:
      NODE_ENV: development
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:3000"  # admin
      - "81:8080"  # main
      - "82:8081"  # chat
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge