version: "3.9"

services:
  backend1:
    build:
      context: .
      dockerfile: ./backend/server/Dockerfile
    ports:
      - "3000:3000"  # main.js
      - "8080:8080"  # admin.js
    volumes:
      - ./database:/app/database
    environment:
      NODE_ENV: development
    networks:
      - app-network

  backend2:
    build:
      context: .
      dockerfile: ./backend/server/Dockerfile
    volumes:
      - ./database:/app/database
    environment:
      NODE_ENV: development
    networks:
      - app-network

  backend3:
    build:
      context: .
      dockerfile: ./backend/server/Dockerfile
    volumes:
      - ./database:/app/database
    environment:
      NODE_ENV: development
    networks:
      - app-network

  chat:
    build:
      context: .
      dockerfile: ./backend/chat/Dockerfile
    volumes:
      - ./database:/app/database
    environment:
      NODE_ENV: development
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:3000"  # admin
      - "81:8080"  # main
      - "82:8081"  # chat
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3
      - chat
    networks:
      - app-network

networks:
  app-network:
    driver: bridge